const exerciseData = [
  {
    id: 'squat',
    name: 'Squat',
    bodyPart: 'Lower Body',
    target: 'Legs',
    gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2021/06/bodyweight-squat-2.gif',
    difficulty: 'Intermediate',
    equipment: 'Barbell or Dumbbells',
    instructions: '1. Stand with your feet shoulder-width apart.\n2. Bend your knees and lower your hips as if sitting back into a chair.\n3. Keep your chest up and core engaged.\n4. Push through your heels to return to the starting position.',
  },
  {
    id: 'bicep-curl',
    name: 'Bicep Curl',
    bodyPart: 'Upper Body',
    target: 'Arms',
    gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2023/01/inner-bicep-curl.gif',
    difficulty: 'Beginner',
    equipment: 'Dumbbells or Barbell',
    instructions: '1. Stand with a dumbbell in each hand, palms facing forward.\n2. Keep your elbows close to your sides and curl the weights up towards your shoulders.\n3. Squeeze your biceps at the top of the movement.\n4. Slowly lower the weights back down to the starting position.',
  },
  {
    id: 'sit-ups',
    name: 'Sit Ups',
    bodyPart: 'Core',
    target: 'Abs',
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2015/11/Crunch.gif',
    difficulty: 'Beginner',
    equipment: 'None',
    instructions: '1. Lie on your back with your knees bent and feet flat on the floor.\n2. Place your hands behind your head or cross them over your chest.\n3. Engage your core and lift your upper body off the ground towards your knees.\n4. Slowly lower your upper body back down to the starting position.',
  },
  {
    id: 'hammer-curls',
    name: 'Hammer Curls',
    bodyPart: 'Upper Body',
    target: 'Arms',
    gifUrl: 'https://www.fitundattraktiv.de/wp-content/uploads/2018/09/hammer_curls_kurzhantel-beidarmig-stehend.gif',
    difficulty: 'Intermediate',
    equipment: 'Dumbbells',
    instructions: '1. Stand with a dumbbell in each hand, palms facing your torso.\n2. Keep your elbows close to your sides and curl the weights up towards your shoulders.\n3. Maintain the palm-facing position throughout the movement.\n4. Slowly lower the weights back down to the starting position.',
  },
  {
    id: 'skullcrushers',
    name: 'Skullcrushers',
    bodyPart: 'Upper Body',
    target: 'Arms',
    gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/08/incline-skullcrusher.gif',
    difficulty: 'Intermediate',
    equipment: 'Barbell or EZ bar',
    instructions: '1. Lie on a bench with a barbell or EZ bar extended over your chest.\n2. Lower the bar towards your forehead by bending your elbows.\n3. Keep your upper arms perpendicular to the floor.\n4. Extend your arms back up to the starting position.',
  },
  {
    id: 'lat-rows',
    name: 'Lat Rows',
    bodyPart: 'Upper Body',
    target: 'Back',
    gifUrl: 'https://liftingfaq.com/wp-content/uploads/2022/11/dumbbell-single-arm-row.gif',
    difficulty: 'Intermediate',
    equipment: 'Barbell or Dumbbells',
    instructions: '1. Stand with your feet shoulder-width apart, knees slightly',
  },
  {
    id: 'rear-delt-flys',
    name: 'Rear Delt Flys',
    bodyPart: 'Shoulders',
    target: 'Rear Deltoids',
    gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2021/11/dumbbell-rear-delt-fly.gif',
    difficulty: 'Intermediate',
    equipment: 'Dumbbells',
    instructions: '1. Hold a dumbbell in each hand with your palms facing inward.\n2. Bend forward at the waist, keeping your back straight.\n3. Raise your arms out to the sides, squeezing your shoulder blades together.\n4. Slowly lower the weights back down to the starting position.',
  },
  {
    id: 'lateral-raises',
    name: 'Lateral Raises',
    bodyPart: 'Shoulders',
    target: 'Side Deltoids',
    gifUrl: 'https://homeworkouts.org/wp-content/uploads/anim-dumbbell-lateral-raise.gif',
    difficulty: 'Intermediate',
    equipment: 'Dumbbells',
    instructions: '1. Stand with a dumbbell in each hand, palms facing your sides.\n2. Keeping your arms straight, raise the weights out to the sides.\n3. Continue raising until your arms are parallel to the floor.\n4. Slowly lower the weights back down to the starting position.',
  },
  {
    id: 'dumbbell-press',
    name: 'Dumbbell Press',
    bodyPart: 'Upper Body',
    target: 'Chest',
    gifUrl: 'https://newlife.com.cy/wp-content/uploads/2019/11/16241301-Dumbbell-Reverse-Bench-Press_Chest_360.gif',
    difficulty: 'Intermediate',
    equipment: 'Dumbbells',
    instructions: '1. Lie on a bench with a dumbbell in each hand, palms facing forward.\n2. Extend your arms upward, directly above your shoulders.\n3. Lower the weights down to the sides of your chest.\n4. Press the weights back up to the starting position.',
  },
  {
    id: 'push-ups',
    name: 'Push Ups',
    bodyPart: 'Upper Body',
    target: 'Chest, Triceps',
    gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/05/weighted-push-up.gif',
    difficulty: 'Beginner',
    equipment: 'None',
    instructions: '1. Start in a high plank position with your hands slightly wider than shoulder-width apart.\n2. Lower your body down by bending your elbows, keeping your body straight.\n3. Push yourself back up to the starting position.\n4. Repeat for the desired number of reps.',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    bodyPart: 'Lower Body',
    target: 'Legs',
    gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/bulgarian-split-spuat.gif',
    difficulty: 'Intermediate',
    equipment: 'Dumbbells or Barbell',
    instructions: '1. Stand with one foot forward and the other foot resting on a bench behind you.\n2. Lower your body down by bending your front knee.\n3. Keep your chest up and core engaged.\n4. Push through your front heel to return to the starting position.',
  },
  {
    id: 'calf-raises',
    name: 'Calf Raises',
    bodyPart: 'Lower Body',
    target: 'Calves',
    gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2021/06/single-leg-standing-calf-raise.gif',
    difficulty: 'Beginner',
    equipment: 'None',
    instructions: '1. Stand on the edge of a step or platform with the balls of your feet.\n2. Raise your heels as high as possible.\n3. Lower your heels back down below the step.\n4. Repeat for the desired number of reps.',
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    bodyPart: 'Lower Body',
    target: 'Legs, Back',
    gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2021/11/dumbbell-romanian-deadlift.gif',
    difficulty: 'Intermediate',
    equipment: 'Barbell or Dumbbells',
    instructions: '1. Stand with your feet shoulder-width apart and the barbell or dumbbells in front of you.\n2. Hinge at your hips and bend your knees slightly.\n3. Grasp the barbell or dumbbells with an overhand grip.\n4. Keeping your back straight, lift the weights by extending your hips and knees.',
  },
  {
    id: 'crunches',
    name: 'Crunches',
    bodyPart: 'Core',
    target: 'Abs',
    gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/12/knee-touch-crunch.gif',
    difficulty: 'Beginner',
    equipment: 'None',
    instructions: '1. Lie on your back with your knees bent and feet flat on the floor.\n2. Place your hands behind your head or cross them over your chest.\n3. Engage your core and lift your shoulder blades off the ground.\n4. Slowly lower your upper body back down to the starting position.',
  },
  {
    id: 'leg-raises',
    name: 'Leg Raises',
    bodyPart: 'Core',
    target: 'Lower Abs',
    gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/06/lying-leg-raise.gif',
    difficulty: 'Intermediate',
    equipment: 'None',
    instructions: '1. Lie on your back with your legs straight and hands by your sides.\n2. Lift your legs off the ground, keeping them together.\n3. Raise your legs until they are perpendicular to the floor.\n4. Slowly lower your legs back down to the starting position.',
  },
  {
    id: 'plank',
    name: 'Plank',
    bodyPart: 'Core',
    target: 'Abs, Core',
    gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/11/body-saw-plank.gif',
    difficulty: 'Beginner',
    equipment: 'None',
    instructions: '1. Start in a high plank position with your forearms on the ground.\n2. Keep your body in a straight line from head to toe.\n3. Engage your core and hold the position for the desired duration.\n4. Relax and repeat for additional sets.',
  },
];

export default exerciseData;
